services:
  - name: telegram-bot
    type: web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot/main.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: PAYMENT_PROVIDER_TOKEN
        sync: false
